#pragma once

//These are the operators, keywords, and delimiters used in parser.h
#define symPERIOD	1
#define symNOT		2
#define symBNOT		3
#define symPP		4
#define symSS		5
#define symMUL          6
#define symDIV          7
#define symMODE		8
#define symADD          9
#define symSUB          10	
#define symBLS		11
#define symBRS		12
#define symBIG		13
#define symSMALL	14
#define symBIGE		15
#define symSMALLE	16
#define symEQUAL	17
#define symNEQUAL	18
#define symBAND		19
#define symBXOR		20
#define symBOR		21
#define symAND		22
#define symOR		23
#define symQUES		24
#define symCOLON	25
#define symPASS       26
#define symAPASS	27
#define symSPASS	28
#define symMPASS	29
#define symDPASS	30
#define symPPASS	31
#define symBAPASS	32
#define symBXPASS	33
#define symBOPASS	34
#define symBLSPASS	35
#define symBRSPASS	36
#define symCOMMA      37
#define symLBRAS      38
#define symRBRAS      39
#define symLBRAM      40
#define symRBRAM      41
#define symLBRAL      42
#define symRBRAL      43
#define symSEMI       44
#define symID         45
#define symNUM        46
#define symSQM        47
#define symNULL		48
#define symINT		49
#define symCHAR		50
#define symDOUBLE	51
#define symRETURN	52
#define symIF		53
#define symELSE		54
#define symDO		55
#define symWHILE	56
#define symBREAK	57
#define symCON		58
#define symFOR		59
#define symENUM		60
#define symCONST	61
#define symSTATIC	62
#define symINCLUDE	63
#define symDEFINE	64
#define symHASH		65
#define symALPHA	66
#define symUNKNOWN	67
#define symSQQM		68
#define symSLIDE	69
#define symPRINT	70
#define symSTRUCT	71
#define symPOS		100		
#define symNEG		101		
#define NUMBER		117
